#ifndef FALLBACKS_H
#define FALLBACKS_H

#define INITIAL_WINDOW_LONG_AXIS	640
#define INITIAL_WINDOW_SHORT_AXIS	512

// opaque white
#define FALLBACK_PAPER_COLOUR_NAME	"White"
#define FALLBACK_PAPER_COLOUR_RED	1.0
#define FALLBACK_PAPER_COLOUR_GREEN	1.0
#define FALLBACK_PAPER_COLOUR_BLUE	1.0
#define FALLBACK_PAPER_COLOUR_ALPHA	1.0

#define FALLBACK_PAPER_ORIENTATION	GTK_PAGE_ORIENTATION_LANDSCAPE
#define FALLBACK_PAPER_SIZE		GTK_PAPER_NAME_LETTER

// opaque black
#define FALLBACK_PEN_COLOUR_NAME	"Black"
#define FALLBACK_PEN_COLOUR_RED		0.0
#define FALLBACK_PEN_COLOUR_GREEN	0.0
#define FALLBACK_PEN_COLOUR_BLUE	0.0
#define FALLBACK_PEN_COLOUR_ALPHA	1.0

#define FALLBACK_PEN_LW_IDX		STANDARD_LINE_WIDTH_0
#define FALLBACK_PEN_LS_IDX		STANDARD_LINE_STYLE_LINE

#define FALLBACK_DRAWING_UNIT		GTK_UNIT_INCH
#define FALLBACK_DRAWING_UUPDU		1.0
#define FALLBACK_DRAWING_ORG_X		0.0
#define FALLBACK_DRAWING_ORG_Y		0.0
#define FALLBACK_DRAWING_SHOW_ORG	FALSE
#define FALLBACK_DRAWING_SHOW_GRID	FALSE
#define FALLBACK_DRAWING_SNAP_GRID	FALSE
#define FALLBACK_DRAWING_TARGET_GRID	NAN

#define FALLBACK_FONT			"Serif"
#define FALLBACK_ALIGNMENT		PANGO_ALIGN_LEFT
#define FALLBACK_JUSTIFY		FALSE
#define FALLBACK_TEXTSIZE		1.0


#endif  /* FALLBACKS_H */
